# Generated by Django 4.2.15 on 2024-09-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
