# Generated by Django 4.2.15 on 2024-09-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_interest_user_interests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="interests",
        ),
        migrations.DeleteModel(
            name="Interest",
        ),
    ]
