# User interests list
INTERESTS = [
    'House cleaning',
    'Handyman',
    'Mechanic',
    'Sales',
    'Designer',
    'Marketing',
    'Legal Consulting',
    'Beauty',
    'Events',
    'Barbershop',
    'Coffeshop',
    'Restaurants and food',
    'Buisness',
    'Real estate',
    'Rent',
    'Finance',
    'Vehicles',
    'Fashion',
    'Jobs',
    'Places Near me',
    'Other',
]
