# User interests list

INTERESTS = [
    'Events',
    'Real estate',
    'Vehicles',
    'Fashion',
    'Jobs',
    'Kids',
    'Furniture',
    'Services',
    'Electronics',
    'Sports & Hobby',
    'Cars',
    'Motorcycle',
    'Truck',
    'Bike',
    'Boat',
    'Van',
    'Scooter',
    'Spare Parts/Accessories',
    'Rentals',
    'House',
    'Apartment',
    'Land',
    'Mobile Home',
    'Commercial',
    'Bedroom',
    'Suite',
    'Studio',
    'Vacation Home',
    'Basement',
    'Cleaning',
    'Handyman',
    'Drivers',
    'Landscaping',
    'Consultancy',
    'Home Automation',
    'Classes and Courses',
    'Personal Training',
    'Construction',
    'Technology',
    'Travel & Visa',
    'Event Services',
    'Farm & Fresh Food',
    'Video & Photography',
    'Interior Design',
    'Homemade Food',
    'Insurance Services ',
    'Home Care (Health)',
    'Catering',
    'Chef',
    'Influencer',
    'AC Services',
    'Personal Trainer ',
    'Cake',
    'Finger Food',
    'Buffet',
    'Transport ',
    'Services',
    'Consulting',
    'Networking Events',
    'Concert',
    'Festival',
    'Full-time ',
    'Part-time',
    'Freelancer',
    'Helper',
    'Home Office',
    'Smartphones',
    'Computers',
    'Appliances',
    'Games',
    'Services and Parts',
    'Couch',
    'Tables ',
    'Chairs',
    'Beds',
    'Custom Furniture',
    'Clothes ',
    'Shoes',
    'Accessories',
    'Beauty Products',
    'Jewelry',
    'Health ',
    'Toys',
    'Transport',
    'Accessories',
    'Classes',
    'Babysitter',
    'Daycare',
    'School Offices',
    'Afterschool Program',
    'Activities',
    'Sports Equipment',
    'Musical Instruments',
    'Collection Items ',
    'Games',
    'Camping',
    'Activities',
]
