from .meta import CONFIRMATION


class RealEstateConstants:
    '''
    Real_Estate Category Constants.
    '''

    BASEMENT = CONFIRMATION
    FURNISHED = ['FURNISHED', 'UNFURNISHED']
    LEASE_TERMS = ['DURATION', 'RENEWAL']
    CREDIT_SCORE_REQ = CONFIRMATION
    UTILITIES = ['WATER', 'GAS', 'ELECTRICITY']
    AMENITIES = ['POOL', 'GYM', 'LAUNDRY']
    ADDITIONAL_FEES = ['APPLICATION FEE', 'SECURITY DEPOSIT', 'MOVE-IN FEE']
    PET_POLICY = [
        'ALLOWED',
        'NOT ALLOWED',
        'ADDITIONAL PET FEE',
        'RESTRICTIONS',
    ]
    RENTERS_INSURANCE = ['REQUIRED', 'NOT REQUIRED']
    SECURITY_MEASURE = ['GATED COMMUNITY', 'SECURITY CAMERAS']
    LEASE_MANAGED_BY = ['OWNER', 'AGENCY']
    CONDITION = ['USED', 'NEW']

    # EXTRAS FOR ESTATE CONSTANTS
    # BEDROOMS
    BATHROOM_TYPE = ['PRIVATE', 'SHARED']
    KITCHEN_ACCESS_TYPE = CONFIRMATION
    LAUNDRY_FACILITIES = ['IN-UNIT', 'ON-SITE', 'OFF-SITE']
    BEDROOM_ADDITIONAL_FEES = CONFIRMATION
    SMOKING_POLICY = ['ALLOWED', 'NOT ALLOWED']
    SECURITY_FEATURES = ['LOCKS', 'CAMERAS']
    NEGOTIABLE = CONFIRMATION
    PREFERRED_OCCUPANTS = [
        'MEN ONLY',
        'WOMEN ONLY',
        'COUPLES WELCOME',
        'SINGLE OCCUPANCY',
        'NO PREFERENCE',
    ]
