from .category import CONFIRMATION


class ServicesConstants:
    '''
    Services Category Constants
    '''

    INSURANCE = ['REQUIRED', 'NOT REQUIRED']
    PAYMENT_OPTION = ['CASH', 'CREDIT CARD', 'ZELLE', 'VENMO', 'PAYPAL', 'PIX']
    CLEANING_SERVICES = [
        'DEEP CLEANING',
        'STANDARD CLEANING',
        'MOVE-IN/MOVE-OUT',
        'POST CONSTRUCTION',
        'ORGANIZATION',
        'UPHOLSTERY CLEANING',
        'PRESSURE WASHING',
        'HOUSE KEEPING',
    ]
    EVENT_TYPES = ['WEDDINGS', 'CORPORATE EVENTS', 'PARTIES', 'OTHER (SPECIFY)']
    CUSTOMIZABLE_PACKAGE = CONFIRMATION
    PACKING_MATERIALS = CONFIRMATION
    GOODS_TRANSIT_INSURANCE = CONFIRMATION
    ECO_FRIENDLY_PRODUCTS = CONFIRMATION
    ORGANIC_SOURCED = CONFIRMATION
    DIFFERENT_PACKAGES = CONFIRMATION
    REGULAR_DELIVERY_OPTION = CONFIRMATION
    DELIVERY_AVAILABILITY = CONFIRMATION
    RECURRING_SERVICE_PLAN = CONFIRMATION
    EQUIPMENT_PROVIDED = CONFIRMATION
    CERTIFICATION = CONFIRMATION
    FURNITURE_SELECTION = CONFIRMATION
    RENDERING_VISUALIZING = CONFIRMATION
    HOMEMADE_SERVICE = CONFIRMATION
    MENU_CUSTOMIZATION = CONFIRMATION
    CONDITION = ['USED', 'NEW']

    # HANDYMAN
    HANDYMAN_SPECIFIC_SERVICES = [
        'PLUMBING',
        'ELECTRICAL',
        'CARPENTRY',
        'GENERAL REPAIRS',
        'OTHER SPECIFIC SERVICES (SPECIFY)',
    ]
    SAME_DAY_SERVICE = CONFIRMATION

    # DRIVING SERVICES
    DRIVING_SERVICES = [
        'PERSONAL DRIVERS',
        'DELIVERIES',
        'AIRPORT TRANSFERS',
        'LONG TRIP AVAILABILITY',
        'RECURRING RIDES',
    ]
    AVAILABLE_VEHICLES = [
        'SEDAN',
        'SUV',
        'LUXURY CAR',
        'VAN',
        'OTHER (SPECIFY)',
    ]

    # LANDSCAPING
    LANDSCAPING_SERVICES = [
        'MOWING',
        'PLANTING',
        'DESIGN',
        'IRRIGATION',
        'LIGHTING',
        'SNOW REMOVAL',
        'OTHER (SPECIFY)',
    ]
    REGULAR_MAINTENANCE = CONFIRMATION
    SEASONAL_SERVICES = ['SEASONAL SERVICES', 'ONE-TIME SERVICES']

    # CONSULTANCY
    CONSULTANCY_LANDSCAPING_SERVICES = [
        'BUSINESS',
        'MARKETING',
        'FINANCE',
        'OTHER (SPECIFY)',
    ]
    SERVICE_AVAILABLE = ['IN-PERSON', 'REMOTELY', 'BOTH']

    # HOME AUTOMATION
    AUTOMATION_SERVICES = [
        'SECURITY',
        'LIGHTING',
        'ENTERTAINMENT',
        'CLIMATE CONTROL',
        'OTHER (SPECIFY)',
    ]

    # CLASSES AND COURSES
    CLASSES_FORMAT = ['ONLINE', 'IN-PERSON', 'BOTH']

    # PERSONAL TRAINING
    TRAINING_OFFERED = [
        'FITNESS',
        'WEIGHT LOSS',
        'STRENGTH TRAINING',
        'DANCE',
        'CIRCUIT TRAINING',
        'OTHER (SPECIFY)',
    ]
    PERSONALISED_FITNESS_PLAN = ['INCLUDED', 'NOT INCLUDED']
    GROUP_SESSION = CONFIRMATION

    # CONSTRUCTION
    CONSTRUCTION_SERVICES = [
        'RESIDENTIAL',
        'COMMERCIAL',
        'RENOVATION',
        'OTHER (SPECIFY)',
    ]

    # TECHNOLOGY
    EXPERTISE_LEVEL = ['BEGINNER', 'INTERMEDIATE', 'ADVANCED']
    TECHNOLOGY_SERVICES = [
        'IT SUPPORT',
        'SOFTWARE DEVELOPMENT',
        'HARDWARE REPAIR',
        'OTHER (SPECIFY)',
    ]
    DELIVERY_METHOD = ['ON-SITE', 'REMOTELY', 'BOTH']
    ONGOING_SUPPORT = CONFIRMATION

    # IMMIGRATION & VISA
    VISA_SERVICES = [
        'VISA APPLICATIONS',
        'GREEN CARD APPLICATIONS',
        'NATURALIZATION SERVICES',
        'STUDENT VISA SERVICES',
        'INVESTOR VISA SERVICES',
        'WORK PERMIT APPLICATIONS',
        'FAMILY SPONSORSHIP',
        'ASYLUM',
        'CITIZENSHIP',
    ]
    FREE_APPOINTMENTS = CONFIRMATION
