'''
---------------------------------------------------
Project:        Braelo
Date:           Aug 14, 2024
Author:         Hamid
---------------------------------------------------

Description:
Django settings for Braelo project.

Generated by 'django-admin startproject' using Django 4.2.15.
---------------------------------------------------
'''

import os
from pathlib import Path
import logging
from dotenv import load_dotenv
from firebase_admin import initialize_app, credentials
from mongoengine import connect
from django.core.exceptions import ValidationError
# Load environment variables
load_dotenv()

FIREBASE_CREDENTIALS = os.getenv("FIREBASE_CREDENTIALS")
project_root = Path(__file__).parent.parent  # Assumes settings.py is inside 'config'
cred_path = project_root / FIREBASE_CREDENTIALS

# Log the credentials path
# logging.info(f"Using Firebase credentials from: {cred_path}")

# # Initialize Firebase
# if not cred_path.exists():
#     raise FileNotFoundError(f"Firebase credentials file not found at: {cred_path}")

try:
    cred = credentials.Certificate(str(cred_path))
    initialize_app(cred)
except Exception:
    # logging.error(f"Failed to initialize Firebase: {e}")
    # raise ValidationError({'Error': 'Failed to initialize Firebase'})
    pass

GOOGLE_OAUTH_CLIENT_ID = (
    "221272028067-cnm21hi90qmfp0jggj62148fetbv8qbn.apps.googleusercontent.com"
)


# We need these lines below to allow the Google sign in popup to work.
SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (
    'django-insecure-d(rn*9qo8w(8^+06+f481^h-ncd8^5*2b%&f0dp&_yc4bgsdo8'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '192.168.18.4',
    'localhost',
    '127.0.0.1',
    'braelo-fug5gcb6c0hpbpdn.canadacentral-01.azurewebsites.net',
]
CORS_ORIGIN_ALLOW_ALL = True
CSRF_TRUSTED_ORIGINS = [
    'https://braelo-fug5gcb6c0hpbpdn.canadacentral-01.azurewebsites.net',
    'http://localhost',
    'http://127.0.0.1',
    'http://192.168.18.4',
]

# Email backend

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# for testing
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# SMTP server settings
EMAIL_HOST = 'smtp.gmail.com'  # Gmail SMTP server (adjust for other providers)
EMAIL_PORT = 587  # Typically 587 for TLS
EMAIL_USE_TLS = True  # Use TLS (Transport Layer Security) for security

# Your email address and password
EMAIL_HOST_USER = 'braelo.fl@gmail.com'
EMAIL_HOST_PASSWORD = 'kgpv txaa anwb bvke'
DEFAULT_FROM_EMAIL = 'braelo.fl@gmail.com'

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'users',
    'chats',
    'listings',
    'notifications',
    'fcm_django',
]

AUTH_USER_MODEL = 'users.User'

# JWT settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'PAGE_SIZE': 15,
}

# Set up JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'BLACKLIST_AFTER_ROTATION': True,
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=2880),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
    'SLIDING_TOKEN_LIFETIME': timedelta(days=30),
    'SLIDING_TOKEN_REFRESH_LIFETIME_LATE_USER': timedelta(days=1),
    'SLIDING_TOKEN_LIFETIME_LATE_USER': timedelta(days=30),
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'applications.custom_authentication.middleware.JWTAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CHANNEL_LAYERS = {
    'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'}
}
# S3 configurations
AZURE_ACCOUNT_NAME = 'braelos3'
AZURE_ACCOUNT_KEY = '5PkRWE5PK49PotcquKuVgZ6jLN261i8VNuqqdpTKJJekYcr2EWwrrlRyqV/s7a+mLOrV/YKBZDOX+AStNDj6pQ=='
AZURE_CONTAINER_NAME = 'braelo'
AZURE_CUSTOM_DOMAIN = 'https://braelos3.blob.core.windows.net/braelo'

# Twilio Setting
TWILIO_ACCOUNT_SID = 'ACd73fc3ad8cee9529a484342740e6161b'
TWILIO_AUTH_TOKEN = 'ef5f648b70cf84215b51e54d44037013 '
TWILIO_VERIFY_SERVICE_SID = 'VAcd6f5d07809c6f1e0d61f76bb64ce123'

# Firebase notifications
FCM_DJANGO_SETTINGS = {
    "FCM_SERVER_KEY": "your-fcm-server-key-here",
}


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'config.wsgi.application'

ASGI_APPLICATION = 'config.asgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
username = 'braelofl'
password = '83PsPZiwdBsgEJNT'
db_name = 'braelo'
connection_string = f"mongodb+srv://{username}:{password}@braelo.karg4.mongodb.net/{db_name}?retryWrites=true&w=majority"

connect(
    db='braelo',  # Name of your MongoDB database
    host=connection_string,
    port=27017,  # Default MongoDB port
    username=username,  # MongoDB username if authentication is enabled
    password=password,  # MongoDB password
    authentication_source='admin',  # Authentication source, usually 'admin'
    # authentication_mechanism='SCRAM-SHA-1',  # Authentication mechanism
)

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
