'''
---------------------------------------------------
Project:        Braelo
Date:           Aug 14, 2024
Author:         Hamid
---------------------------------------------------

Description:
Braelo constants.
---------------------------------------------------
'''

# Subcategories
VEHICLES = [
    'Cars',
    'Motorcycle',
    'Truck',
    'Bike',
    'Boat',
    'Van',
    'Scooter',
    'Parts and Accessories',
    'Rentals',
]
REAL_ESTATE = [
    'House',
    'Apartment',
    'Land',
    'Mobile Home',
    'Commercial',
    'Bedroom',
    'Suite',
    'Studio',
    'Vacation Home',
    'Basement',
]
Services = [
    'Cleaning',
    'Handyman',
    'Drivers',
    'Landscaping',
    'Consultancy',
    'Home Automation',
    'Classes & Courses',
    'Personal Training',
    'Construction',
    'Technology',
    'Immigration and Visa',
    'Event Services',
    'Movers & Packers',
    'Farm & Fresh Food',
    'Video & Photography',
    'Interior Design',
    'Homemade Food',
    'Insurance Services',
    'Home Care (Health)',
    'Catering',
    'Chef',
    'Influencer',
    'AC Services',
    'Personal Trainer',
    'Cake',
    'Finger Food',
    'Buffet',
    'Transport Services',
]
EVENTS = ['Networking Events', 'Concert', 'Festival']
JOBS = ['Full Time', 'Part Time', 'Freelancer', 'Helper', 'Home Office']
ELECTRONICS = [
    'Smartphones',
    'Computers',
    'Appliances',
    'Games',
    'Services & Parts',
]
FURNITURE = ['Couch', 'Tables', 'Chairs', 'Beds', 'Custom Furniture']
FASHION = ['Clothes', 'Shoes', 'Accessories', 'Beauty Products', 'Jewelry']
KIDS = [
    'Health',
    'Toys',
    'Transport',
    'Accessories',
    'Classes',
    'Babysitter',
    'Daycare',
    'School Offices',
    'Afterschool Program',
    'Activities',
]
SPORTS_HOBBY = [
    'Sports Equipment',
    'Musical Instruments',
    'Collected Items',
    'Games',
    'Camping',
    'Outdoor Activities',
]


# Categories
CATEGORIES = {
    'vehicles': VEHICLES,
    'real estate': REAL_ESTATE,
    'services': Services,
    'events': EVENTS,
    'jobs': JOBS,
    'electronics': ELECTRONICS,
    'furniture': FURNITURE,
    'fashion': FASHION,
    'kids': KIDS,
    'sports & hobby': SPORTS_HOBBY,
}

# GENRALS
CONFIRMATION = ['YES', 'NO']

# VEHICLE LISTINGS CONSTANTS
TRANSMISSION = ['AUTOMATIC', 'MANUAL']
CONDITION = ['USED', 'NEW']
NUMBER_OF_DOORS = ['1/3', '4/5']
PURPOSE = ['SALE', 'RENTAL']
FOR_SALE = CONFIRMATION
RENTALS = CONFIRMATION
NEGOTIABLE = CONFIRMATION

# REAL ESTATE CONSTANTS
# APARTMENT
BASEMENT = CONFIRMATION
FURNISHED = ['FURNISHED', 'UNFURNISHED']
LEASE_TERMS = ['DURATION', 'RENEWAL']
CREDIT_SCORE_REQ = CONFIRMATION
UTILITIES = ['WATER', 'GAS', 'ELECTRICITY']
AMENITIES = ['POOL', 'GYM', 'LAUNDRY']
ADDITIONAL_FEES = ['APPLICATION FEE', 'SECURITY DEPOSIT', 'MOVE-IN FEE']
PET_POLICY = ['ALLOWED', 'NOT ALLOWED', 'ADDITIONAL PET FEE', 'RESTRICTIONS']
RENTERS_INSURANCE = ['REQUIRED', 'NOT REQUIRED']
SECURITY_MEASURE = ['GATED COMMUNITY', 'SECURITY CAMERAS']
LEASE_MANAGED_BY = ['OWNER', 'AGENCY']

# EXTRAS FOR ESTATE CONSTANTS
# BEDROOMS
BATHROOM_TYPE = ['PRIVATE', 'SHARED']
KITCHEN_ACCESS_TYPE = CONFIRMATION
LAUNDRY_FACILITIES = ['IN-UNIT', 'ON-SITE', 'OFF-SITE']
BEDROOM_ADDITIONAL_FEES = CONFIRMATION
SMOKING_POLICY = ['ALLOWED', 'NOT ALLOWED']
SECURITY_FEATURES = ['LOCKS', 'CAMERAS']
PREFERRED_OCCUPANTS = [
    'MEN ONLY',
    'WOMEN ONLY',
    'COUPLES WELCOME',
    'SINGLE OCCUPANCY',
    'NO PREFERENCE',
]

# SERVICES CONSTANTS
# CLEANING
INSURANCE = ['REQUIRED', 'NOT REQUIRED']
PAYMENT_OPTION = ['CASH', 'CREDIT CARD', 'ZELLE', 'VENMO', 'PAYPAL', 'PIX']
CLEANING_SERVICES = [
    'DEEP CLEANING',
    'STANDARD CLEANING',
    'MOVE-IN/MOVE-OUT',
    'POST CONSTRUCTION',
    'ORGANIZATION',
    'UPHOLSTERY CLEANING',
    'PRESSURE WASHING',
    'HOUSE KEEPING',
]

ECO_FRIENDLY_PRODUCTS = CONFIRMATION
EQUIPMENT_PROVIDED = CONFIRMATION
CERTIFICATION = CONFIRMATION

# HANDYMAN
HANDYMAN_SPECIFIC_SERVICES = [
    'PLUMBING',
    'ELECTRICAL',
    'CARPENTRY',
    'GENERAL REPAIRS',
    'OTHER SPECIFIC SERVICES (SPECIFY)',
]
SAME_DAY_SERVICE = CONFIRMATION

# DRIVING SERVICES
DRIVING_SERVICES = [
    'PERSONAL DRIVERS',
    'DELIVERIES',
    'AIRPORT TRANSFERS',
    'LONG TRIP AVAILABILITY',
    'RECURRING RIDES',
]
AVAILABLE_VEHICLES = ['SEDAN', 'SUV', 'LUXURY CAR', 'VAN', 'OTHER (SPECIFY)']

# LANDSCAPING
LANDSCAPING_SERVICES = [
    'MOWING',
    'PLANTING',
    'DESIGN',
    'IRRIGATION',
    'LIGHTING',
    'SNOW REMOVAL',
    'OTHER (SPECIFY)',
]
REGULAR_MAINTENANCE = CONFIRMATION
SEASONAL_SERVICES = ['SEASONAL SERVICES', 'ONE-TIME SERVICES']

# CONSULTANCY
CONSULTANCY_LANDSCAPING_SERVICES = [
    'BUSINESS',
    'MARKETING',
    'FINANCE',
    'OTHER (SPECIFY)',
]
SERVICE_AVAILABLE = ['IN-PERSON', 'REMOTELY', 'BOTH']

# HOME AUTOMATION
AUTOMATION_SERVICES = [
    'SECURITY',
    'LIGHTING',
    'ENTERTAINMENT',
    'CLIMATE CONTROL',
    'OTHER (SPECIFY)',
]

# CLASSES AND COURSES
CLASSES_FORMAT = ['ONLINE', 'IN-PERSON', 'BOTH']

# PERSONAL TRAINING
TRAINING_OFFERED = [
    'FITNESS',
    'WEIGHT LOSS',
    'STRENGTH TRAINING',
    'DANCE',
    'CIRCUIT TRAINING',
    'OTHER (SPECIFY)',
]
PERSONALISED_FITNESS_PLAN = ['INCLUDED', 'NOT INCLUDED']
GROUP_SESSION = CONFIRMATION

# CONSTRUCTION
CONSTRUCTION_SERVICES = [
    'RESIDENTIAL',
    'COMMERCIAL',
    'RENOVATION',
    'OTHER (SPECIFY)',
]

# TECHNOLOGY
EXPERTISE_LEVEL = ['BEGINNER', 'INTERMEDIATE', 'ADVANCED']
TECHNOLOGY_SERVICES = [
    'IT SUPPORT',
    'SOFTWARE DEVELOPMENT',
    'HARDWARE REPAIR',
    'OTHER (SPECIFY)',
]
DELIVERY_METHOD = ['ON-SITE', 'REMOTELY', 'BOTH']
ONGOING_SUPPORT = CONFIRMATION

# IMMIGRATION & VISA
VISA_SERVICES = [
    'VISA APPLICATIONS',
    'GREEN CARD APPLICATIONS',
    'NATURALIZATION SERVICES',
    'STUDENT VISA SERVICES',
    'INVESTOR VISA SERVICES',
    'WORK PERMIT APPLICATIONS',
    'FAMILY SPONSORSHIP',
    'ASYLUM',
    'CITIZENSHIP',
]
FREE_APPOINTMENTS = CONFIRMATION

# EVENT SERVICES
EVENT_TYPES = ['WEDDINGS', 'CORPORATE EVENTS', 'PARTIES', 'OTHER (SPECIFY)']
EVENT_SPECIFIC_SERVICES = [
    'PLANNING',
    'CATERING',
    'DECORATION',
    'COORDINATION',
    'OTHER (SPECIFY)',
]
CUSTOMIZABLE_PACKAGE = CONFIRMATION

# MOVING & PACKERS
MOVING_SERVICE = [
    'LOCAL',
    'LONG-DISTANCE',
    'RESIDENTIAL',
    'COMMERCIAL',
    'STORAGE',
    'INTERNATIONALLY',
]
PACKING_MATERIALS = CONFIRMATION
GOODS_TRANSIT_INSURANCE = CONFIRMATION

# FARM FRESH FOOD
PRODUCTS_AVAILABLE = [
    'VEGETABLES',
    'FRUITS',
    'DAIRY',
    'FAIR',
    'LUNCH',
    'COLONIAL COFFEE',
    'OTHER (SPECIFY)',
]
DELIVERY_AVAILABILITY = CONFIRMATION
ORGANIC_SOURCED = CONFIRMATION
REGULAR_DELIVERY_OPTION = CONFIRMATION


# PHOTOGRAPHY AND VIDEOGRAPHY
PHOTOGRAPHY_SERVICES = [
    'WEDDINGS',
    'CORPORATE',
    'PORTRAIT',
    'COMMERCIAL',
    'DRONE',
    'OTHER (SPECIFY)',
]
DIFFERENT_PACKAGES = CONFIRMATION
RECURRING_SERVICE_PLAN = CONFIRMATION

# INTERIOR DESIGN
INTERIOR_DESIGN_SERVICES = [
    'RESIDENTIAL',
    'COMMERCIAL',
    'VIRTUAL',
    'OTHER (SPECIFY)',
]
FURNITURE_SELECTION = CONFIRMATION
RENDERING_VISUALIZING = CONFIRMATION

# HOMEMADE FOOD
AVAILABLE_HOMEMADE_FOOD = [
    'BAKED GOODS',
    'MEALS',
    'SNACKS',
    'FOOD PREP',
    'PERSONAL CHEF',
    'OTHER (SPECIFY)',
]
HOMEMADE_SERVICE = ['DELIVERY', 'PICKUP', 'AT-HOME PREP', 'ALL OF THE ABOVE']

# INSURANCE
INSURANCE_SERVICES = [
    'HEALTH',
    'AUTO',
    'HOME',
    'LIFE',
    'BUSINESS',
    'OTHER (SPECIFY)',
]

# HOME CARE
HOME_CARE_SERVICES = [
    'NURSING',
    'PHYSICAL THERAPY',
    'COMPANIONSHIP',
    'PERSONAL CARE',
    'HOME MAKING',
    'OTHER (SPECIFY)',
]
# Buffet
MENU_CUSTOMIZATION = CONFIRMATION

# JOBS CATEGORY
WORK_PERMIT = CONFIRMATION
HELPER_TOOLS = CONFIRMATION
HELPER_CAR = CONFIRMATION
HELPER_PAY = ['HOUR', 'DAY', 'TASKS']

# FURNITURE
DONATION = CONFIRMATION
MATTRESS_INCLUDED = CONFIRMATION

# KIDS
KIDS_GRADES = [
    'KINDERGARTEN',
    'ELEMENTARY SCHOOL',
    'MIDDLE SCHOOL',
    'HIGH SCHOOL',
    'COLLEGE',
    'UNIVERSITY',
]
